MIN_LINK_UTILZATION = 0.3
MAX_LINK_UTILZATION = 0.7

MIN_PACKET_LOSS_RATE = 0.05
MAX_PACKET_LOSS_RATE = 0.3

MIN_DELAY = 20
MAX_DELAY = 50

##################### ALPHA * PACKET LOSS + BETA * DELAY + GAMMA * LINK UTILIZATION
#### SERVICE 0
ALPHA_FILE_TRANSFER = 0.6
BETA_FILE_TRANSFER = 0.2
GAMMA_FILE_TRANSFER = 0.2
#### SERVICE 1
ALPHA_GOOGLE_MUSIC = 0.2
BETA_GOOGLE_MUSIC = 0.6
GAMMA_GOOGLE_MUSIC = 0.2
#### SERVICE 2
ALPHA_GOOGLEHANGOUT_VOIP = 0.4
BETA_GOOGLEHANGOUT_VOIP = 0.3
GAMMA_GOOGLEHANGOUT_VOIP = 0.2
#### SERVICE 3
ALPHA_YOUTUBE = 0.3
BETA_YOUTUBE = 0.5
GAMMA_YOUTUBE = 0.2



